name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Version mise à jour

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Version mise à jour
        with:
          node-version: '16'  # Ou '20' selon ta préférence

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test